// 1. Create a variable using const and store your college name. Print it
// const name="Geeta"
// console.log(`My college name is ${name}`)

// 2. Create a variable using let and update its value three times
// let age=20
// console.log(`My age is ${age}`)
// age=21
// console.log(`My age is ${age}`)
// age=22
// console.log(`My age is ${age}`)


// 3. Create a block using {} and show that a variable declared with let cannot be accessed
// outside it.
// {let message="Hello"
// {
//     console.log(message)
// }}
// console.log(message)

// 4. Write a program to swap two numbers using array destructuring.
let a=5;
let b=10;
[a,b]=[b,a]
console.log(`a=${a} and b=${b}`);